[pytest]
addopts = --alluredir=allure-results --strict-markers
pythonpath = .
markers =
   smoke: mark test as smoke
   login: mark test as login
   logout: mark test as logout
   admin: mark test as testadmin
   new_user: mark test as create new user
   duplicate: mark test as duplicate user
   required: mark test as required
   search_by_username: mark test as search by username
   search_by_role: mark test as search by role
   search_nonexistent: mark test as search for non-existent user
   edit_user: mark test as edit user
   delete_user: mark test as delete user
   bulk_delete_users: mark test as bulk delete users

[allure]
results_dir = allure-results