[pytest]
addopts = --alluredir=allure-results --strict-markers
pythonpath = .
log_cli = true
log_cli_level = INFO
markers =
   smoke: mark test as smoke
   regression: mark test as regression
   login: mark test as login
   logout: mark test as logout
   view_users: mark test as view users
   admin: mark test as testadmin
   new_user: mark test as create new user
   duplicate: mark test as duplicate user
   required: mark test as required
   search_by_username: mark test as search by username
   search_by_role: mark test as search by role
   search_nonexistent: mark test as search for non-existent user
   edit_user: mark test as edit user
   delete_user: mark test as delete user
   bulk_delete_users: mark test as bulk delete users
   pim: mark test as pim
   view_employees: mark test as view employees
   new_employee: mark test as create new employee
   without_name: mark test as create employee without name
   search_by_name: mark test as search by name
   search_by_id: mark test as search by id
   search_no_results: mark test as search for no results
   view_profile: mark test as view profile
   update_profile: mark test as update profile
   delete_employee: mark test as delete employee
   leave: mark test as leave
   view_leave_types: mark test as view leave types
   apply_leave_valid: mark test as apply leave valid
   apply_leave_past_date: mark test as apply leave past date
   apply_leave_missing_field: mark test as apply leave missing field
   approve_leave: mark test as approving leave
   reject_leave: mark test as rejecting leave
   view_my_leave: mark test as viewing personal leave
   my_info: mark test as my info
   view_personal_info: mark test as viewing personal information
   update_personal_info: mark test as updating personal information
   update_contact_info: mark test as updating contact information
   add_emergency_contact: mark test as adding an emergency contact
   emergency_contact_required: mark test as required emergency contact validation
   invalid_phone: mark test as invalid phone validation

[allure]
results_dir = allure-results